#!/usr/bin/python3

from smlib.core import *
from smlib.format import *
from smlib.info import *
from smlib.create import *
from smlib.trust import *
from smlib.delete import *

keepRunning=True
while keepRunning:
    # Run a sudo command to capture the password as soon as the script is run
    #os.system('clear')
    print("")
    print(color.BBLUE + "QuiverLocal WordPress Development Environment Tool " + background.END)
    print(6 * "-" , "OPTIONS" , 6 * "-")
    print(style.NEGATIVE + "1" + style.END + " List Sites")
    print(style.NEGATIVE + "2" + style.END + " New Install")
    print(style.NEGATIVE + "3" + style.END + " Import Site")
    print(style.NEGATIVE + "4" + style.END + " Add SSL to Site")
    print(style.NEGATIVE + "5" + style.END + " Delete Site")
    print("")
    print(style.NEGATIVE + "0" + style.END + " Exit")
    print(21 * "-")

    selection = int(getInput("Enter option [0-5]: ", True))

    match selection:
        case 0:
            print("Goodbye")
            keepRunning = False
        case 1:
            # Display details about installed sites using the info library
            print("Listing Sites")
            getSiteList(quiverDB)
        case 2:
            print("Install New Site")
            createNewSite()
        case 3:
            print("Import Existing Site")
            importSite()
        case 4:
            print("Add SSL to Existing Site")
            trustSite()
        case 5:
            print("Delete Site")
            deleteSite()
        case 6:
            getTablePrefixes()
        case _:
            print("")
            print(background.BYELLOW + "Unknown selection" + background.END)         
